# This file simulates a database of 50 employees for XYZ Organization with Indian names and experience.
EMPLOYEE_DATA = [
    {
        "id": 1, "name": "Admin User", "username": "admin", "designation": "System Administrator", "email": "admin@xyz.com",
        "salary": 1500000, "attendance_percentage": 99.0, "leaves_taken": 5, "experience_years": 10
    },
    {
        "id": 2, "name": "Priya Sharma", "username": "employee", "designation": "Software Engineer", "email": "priya.sharma@xyz.com",
        "salary": 900000, "attendance_percentage": 96.2, "leaves_taken": 8, "experience_years": 3
    },
    {"id": 3, "name": "Rohan Mehta", "username": "rmehta", "designation": "Project Manager", "salary": 1200000, "attendance_percentage": 99.1, "leaves_taken": 4, "experience_years": 7},
    {"id": 4, "name": "Anjali Singh", "username": "asingh", "designation": "UI/UX Designer", "salary": 850000, "attendance_percentage": 95.0, "leaves_taken": 10, "experience_years": 4},
    {"id": 5, "name": "Vikram Patel", "username": "vpatel", "designation": "Data Scientist", "salary": 1400000, "attendance_percentage": 97.8, "leaves_taken": 6, "experience_years": 6},
    {"id": 6, "name": "Sunita Gupta", "username": "sgupta", "designation": "QA Engineer", "salary": 780000, "attendance_percentage": 98.2, "leaves_taken": 7, "experience_years": 5},
    {"id": 7, "name": "Amit Kumar", "username": "akumar", "designation": "DevOps Engineer", "salary": 1100000, "attendance_percentage": 96.5, "leaves_taken": 8, "experience_years": 6},
    {"id": 8, "name": "Deepika Reddy", "username": "dreddy", "designation": "Product Owner", "salary": 1600000, "attendance_percentage": 99.5, "leaves_taken": 3, "experience_years": 9},
    {"id": 9, "name": "Rajesh Nair", "username": "rnair", "designation": "Software Engineer", "salary": 920000, "attendance_percentage": 94.0, "leaves_taken": 11, "experience_years": 3},
    {"id": 10, "name": "Kavita Joshi", "username": "kjoshi", "designation": "HR Manager", "salary": 1000000, "attendance_percentage": 98.9, "leaves_taken": 5, "experience_years": 8},
    # ... (generating more sample data)
    {"id": 11, "name": "Sanjay Verma", "username": "sverma", "designation": "Marketing Specialist", "salary": 750000, "attendance_percentage": 97.1, "leaves_taken": 7, "experience_years": 4},
    {"id": 12, "name": "Meera Iyer", "username": "miyer", "designation": "Financial Analyst", "salary": 950000, "attendance_percentage": 99.0, "leaves_taken": 4, "experience_years": 5},
    {"id": 13, "name": "Arun Pillai", "username": "apillai", "designation": "Software Engineer", "salary": 880000, "attendance_percentage": 95.8, "leaves_taken": 9, "experience_years": 2},
    {"id": 14, "name": "Lakshmi Rao", "username": "lrao", "designation": "UI/UX Designer", "salary": 820000, "attendance_percentage": 96.3, "leaves_taken": 8, "experience_years": 3},
    {"id": 15, "name": "Gopal Krishnan", "username": "gkrishnan", "designation": "Data Scientist", "salary": 1450000, "attendance_percentage": 97.5, "leaves_taken": 6, "experience_years": 7},
    {"id": 16, "name": "Neha Desai", "username": "ndesai", "designation": "Project Manager", "salary": 1250000, "attendance_percentage": 98.7, "leaves_taken": 5, "experience_years": 8},
    {"id": 17, "name": "Harish Menon", "username": "hmenon", "designation": "DevOps Engineer", "salary": 1150000, "attendance_percentage": 95.5, "leaves_taken": 9, "experience_years": 5},
    {"id": 18, "name": "Pooja Hegde", "username": "phegde", "designation": "QA Engineer", "salary": 800000, "attendance_percentage": 97.9, "leaves_taken": 7, "experience_years": 4},
    {"id": 19, "name": "Manoj Tiwari", "username": "mtiwari", "designation": "Software Engineer", "salary": 930000, "attendance_percentage": 96.8, "leaves_taken": 8, "experience_years": 4},
    {"id": 20, "name": "Rina Biswas", "username": "rbiswas", "designation": "HR Specialist", "salary": 800000, "attendance_percentage": 99.2, "leaves_taken": 4, "experience_years": 3},
    # ... continues for 50 employees
    {"id": 21, "name": "Alok Nath", "username": "anath", "designation": "Marketing Manager", "salary": 1200000, "attendance_percentage": 98.1, "leaves_taken": 6, "experience_years": 9},
    {"id": 22, "name": "Bhavna Bhatt", "username": "bbhatt", "designation": "Financial Controller", "salary": 1700000, "attendance_percentage": 99.8, "leaves_taken": 2, "experience_years": 12},
    {"id": 23, "name": "Chirag Dubey", "username": "cdubey", "designation": "Software Engineer", "salary": 910000, "attendance_percentage": 94.5, "leaves_taken": 10, "experience_years": 3},
    {"id": 24, "name": "Divya Seth", "username": "dseth", "designation": "UI/UX Designer", "salary": 860000, "attendance_percentage": 96.0, "leaves_taken": 8, "experience_years": 4},
    {"id": 25, "name": "Esha Agarwal", "username": "eagarwal", "designation": "Data Scientist", "salary": 1500000, "attendance_percentage": 98.0, "leaves_taken": 5, "experience_years": 8},
    {"id": 26, "name": "Farhan Khan", "username": "fkhan", "designation": "Project Manager", "salary": 1300000, "attendance_percentage": 97.4, "leaves_taken": 7, "experience_years": 7},
    {"id": 27, "name": "Gita Chandra", "username": "gchandra", "designation": "DevOps Engineer", "salary": 1180000, "attendance_percentage": 95.2, "leaves_taken": 9, "experience_years": 6},
    {"id": 28, "name": "Hema Malini", "username": "hmalini", "designation": "QA Engineer", "salary": 820000, "attendance_percentage": 98.3, "leaves_taken": 6, "experience_years": 5},
    {"id": 29, "name": "Irfan Ahmed", "username": "iahmed", "designation": "Software Engineer", "salary": 950000, "attendance_percentage": 96.6, "leaves_taken": 8, "experience_years": 4},
    {"id": 30, "name": "Jaya Prasad", "username": "jprasad", "designation": "HR Generalist", "salary": 780000, "attendance_percentage": 99.3, "leaves_taken": 4, "experience_years": 2},
    {"id": 31, "name": "Kiran Bedi", "username": "kbedi", "designation": "Marketing Analyst", "salary": 760000, "attendance_percentage": 97.2, "leaves_taken": 7, "experience_years": 3},
    {"id": 32, "name": "Lalit Modi", "username": "lmodi", "designation": "Financial Analyst", "salary": 980000, "attendance_percentage": 98.8, "leaves_taken": 5, "experience_years": 6},
    {"id": 33, "name": "Madhavan Nair", "username": "mnair", "designation": "Software Engineer", "salary": 920000, "attendance_percentage": 95.1, "leaves_taken": 9, "experience_years": 3},
    {"id": 34, "name": "Nita Ambani", "username": "nambani", "designation": "UI/UX Designer", "salary": 840000, "attendance_percentage": 96.1, "leaves_taken": 8, "experience_years": 4},
    {"id": 35, "name": "Om Prakash", "username": "oprakash", "designation": "Data Scientist", "salary": 1480000, "attendance_percentage": 97.8, "leaves_taken": 6, "experience_years": 7},
    {"id": 36, "name": "Parvati Patil", "username": "ppatil", "designation": "Project Manager", "salary": 1320000, "attendance_percentage": 98.5, "leaves_taken": 5, "experience_years": 8},
    {"id": 37, "name": "Qadir Ali", "username": "qali", "designation": "DevOps Engineer", "salary": 1200000, "attendance_percentage": 95.9, "leaves_taken": 9, "experience_years": 6},
    {"id": 38, "name": "Rani Mukherjee", "username": "rmukherjee", "designation": "QA Engineer", "salary": 830000, "attendance_percentage": 98.0, "leaves_taken": 6, "experience_years": 5},
    {"id": 39, "name": "Sachin Tendulkar", "username": "stendulkar", "designation": "Software Engineer", "salary": 960000, "attendance_percentage": 96.9, "leaves_taken": 8, "experience_years": 4},
    {"id": 40, "name": "Tara Sutaria", "username": "tsutaria", "designation": "HR Coordinator", "salary": 750000, "attendance_percentage": 99.4, "leaves_taken": 3, "experience_years": 2},
    {"id": 41, "name": "Usha Uthup", "username": "uuthup", "designation": "Marketing Coordinator", "salary": 740000, "attendance_percentage": 97.0, "leaves_taken": 7, "experience_years": 3},
    {"id": 42, "name": "Vivek Oberoi", "username": "voberoi", "designation": "Financial Planner", "salary": 1000000, "attendance_percentage": 98.6, "leaves_taken": 5, "experience_years": 7},
    {"id": 43, "name": "Wasim Akram", "username": "wakram", "designation": "Software Engineer", "salary": 940000, "attendance_percentage": 94.8, "leaves_taken": 10, "experience_years": 3},
    {"id": 44, "name": "Yamini Reddy", "username": "yreddy", "designation": "UI/UX Designer", "salary": 870000, "attendance_percentage": 96.4, "leaves_taken": 8, "experience_years": 4},
    {"id": 45, "name": "Zakir Hussain", "username": "zhussain", "designation": "Data Scientist", "salary": 1550000, "attendance_percentage": 97.9, "leaves_taken": 6, "experience_years": 9},
    {"id": 46, "name": "Anand Mahindra", "username": "amahindra", "designation": "Chief Technical Officer", "salary": 5000000, "attendance_percentage": 99.9, "leaves_taken": 1, "experience_years": 25},
    {"id": 47, "name": "Boman Irani", "username": "birani", "designation": "DevOps Lead", "salary": 1800000, "attendance_percentage": 95.3, "leaves_taken": 9, "experience_years": 14},
    {"id": 48, "name": "Chetan Bhagat", "username": "cbhagat", "designation": "Technical Writer", "salary": 850000, "attendance_percentage": 98.1, "leaves_taken": 6, "experience_years": 10},
    {"id": 49, "name": "Dinesh Karthik", "username": "dkarthik", "designation": "Senior Software Engineer", "salary": 1100000, "attendance_percentage": 96.7, "leaves_taken": 8, "experience_years": 8},
    {"id": 50, "name": "Indra Nooyi", "username": "inooyi", "designation": "CEO", "salary": 8000000, "attendance_percentage": 99.8, "leaves_taken": 2, "experience_years": 30}
]